### ISSUE TITLE
Fix issue with complex passwords

### ISSUE THREAD

**Issue by docktermj** [Senzing/stream-loader#31]
**Describe the bug**
Complex passwords in INI files don't parse.

**Comment by docktermj** [comment]
If the following is in G2Project.ini,

```toml
[g2]
G2Connection=db2://user999:w#lQ%4e_Q04i-5PF@AESEDB
```

will mess up getting the password.
